language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_success:
  - npm run coverage
  - npm run test:docs
  - bash <(curl -s https://codecov.io/bash)
sudo: false
