language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
before_install:
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
after_success:
  - npm run coverage
  - npm run test:docs
  - bash <(curl -s https://codecov.io/bash)
sudo: false
