environment:
    matrix:
        - nodejs_version: '10'
        - nodejs_version: '11'
        - nodejs_version: '12'

install:
    - ps: Install-Product node $env:nodejs_version
    - npm i -g npm@6
    - npm install

test_script:
    - node --version
    - npm --version
    - npm test

build: off
